#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "🔍 SponsorCap Object ID Bulma Rehberi"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📌 Sponsor Wallet: 0x60be68f004e0dde8b2cadaaae37c0a2aadefd7c0eb66f91875e4eb0865e6b623"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Method 1: Sui CLI ile Kontrol"
echo "─────────────────────────────────────────────────────────────"
echo "Terminal'de şu komutu çalıştır:"
echo ""
echo "  sui client objects --json | grep -B 5 -A 10 'SponsorCap'"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Method 2: Sui Explorer ile Kontrol"
echo "─────────────────────────────────────────────────────────────"
echo "1. https://suiexplorer.com/?network=testnet adresine git"
echo "2. Arama kutusuna wallet adresini yapıştır"
echo "3. 'Owned Objects' sekmesinde 'SponsorCap' ara"
echo "4. Object ID'yi kopyala (0x ile başlayan uzun adres)"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Method 3: Eğer SponsorCap Yoksa"
echo "─────────────────────────────────────────────────────────────"
echo "SponsorCap görmüyorsan, önce kayıt olman gerekiyor:"
echo ""
echo "1. Ana sayfaya git (http://localhost:5173)"
echo "2. 'Join the Community' formunu doldur"
echo "3. Role olarak 'Sponsor' seç"
echo "4. Submit'e tıkla ve wallet'ta onayla"
echo "5. İşlem onaylandıktan sonra SponsorCap NFT alacaksın"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "⚠️  ÖNEMLİ NOTLAR"
echo "─────────────────────────────────────────────────────────────"
echo "• SponsorCap ID, wallet adresinden farklıdır!"
echo "• Object ID genellikle şöyle görünür: 0x...64 karakter"
echo "• Testnet'te olduğundan emin ol"
echo "• Wallet'ında yeterli SUI test tokeni olmalı"
echo ""
echo "═══════════════════════════════════════════════════════════════"
