#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "🔄 Move Package Yeniden Yayınlama ve Test Rehberi"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Blockchain'de eski kayıtlar kalıcıdır, bu yüzden yeni bir package"
echo "yayınlayarak temiz bir başlangıç yapacağız."
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Adım 1: Move Package'ı Yeniden Yayınla"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Terminal'de şu komutları çalıştır:"
echo ""
echo "cd blockedy"
echo "sui client publish --gas-budget 100000000"
echo ""
echo "İşlem tamamlandığında:"
echo "1. 'Published Objects' bölümünden yeni Package ID'yi not al"
echo "2. 'Created Objects' bölümünden DeveloperCap ve UpgradeCap ID'leri not al"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Adım 2: Frontend Constants Güncelle"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "src/config/constants.ts dosyasını yeni ID'lerle güncelle:"
echo ""
echo "export const PACKAGE_ID = \"0xYENI_PACKAGE_ID\";"
echo "export const DEVELOPER_CAP_ID = \"0xYENI_DEVELOPER_CAP_ID\";"
echo "export const UPGRADE_CAP_ID = \"0xYENI_UPGRADE_CAP_ID\";"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo "Adım 3: Test Wallet'ları Sırayla Kaydet"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "1. Sponsor (f4kpss1907@gmail.com):"
echo "   0x60be68f004e0dde8b2cadaaae37c0a2aadefd7c0eb66f91875e4eb0865e6b623"
echo ""
echo "2. Contestant (f4kanzyttv):"
echo "   0x60be68f004e0dde8b2cadaaae37c0a2aadefd7c0eb66f91875e4eb0865e6b623"
echo ""
echo "3. Jury 1 (sudenazzehirr):"
echo "   0xc4151953e58edb05fbc77fabcaf428cc611a8ffec62fceeeb715bc46fd68f416"
echo ""
echo "4. Jury 2 (sudekaray):"
echo "   0xddc32010138da3ac8e3cf73c94548ad592dfba787071d6cd9db78a97fac2cde9"
echo ""
echo "5. Jury 3 (ecolo42):"
echo "   0xa55f4ccfe3d683fa133753ba40e9afea3ea865c280804d6aba6242b1ebfdc5ab"
echo ""
echo "6. Extra (sudenazky7):"
echo "   0x1c3e6d51b6d127015f7b3e48118ae30e40b00df311e8b0ddb5c20a92e43ad886"
echo ""
echo "Her wallet için:"
echo "- Ana sayfadaki 'Join the Community' formunu doldur"
echo "- Uygun role seç (Sponsor/Contestant/Jury)"
echo "- Submit ve wallet'ta onayla"
echo "- Explorer'da yeni Cap NFT'yi kontrol et"
echo ""
echo "═══════════════════════════════════════════════════════════════"
